# Generated by Django 6.0.6 on 2026-06-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={},
        ),
        migrations.AddField(
            model_name='update',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='updates_images/'),
        ),
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='update',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
